### ISSUE TITLE
Crates.io release?

### ISSUE THREAD

**Issue by l1npengtul** [FractalFir/wrapped_mono#2]
Is there a plan for a crates.io release?

**Comment by FractalFir** [comment]
There are plans for crates.io release(when version **0.2** is finished), but there are couple issues that need sorting out before it can be done. While `wrapped_mono` compiles on windows, it still requires some work(2 files need to be copied manually to project directory each time it is used). 
Adding project to crates.io would suggest that it can be downloaded and installed automatically by cargo, which is not yet the case. For both of those files there is a "dirty" fix, (changing linking of mono from dynamic to static on windows, and changing default location where C#'s  core libraries, such as`mscorlib.dll`are searched for), but this fix would have it's own problems and require additional work to make them work properly.
I can't give any date, since I am in high school and it will all depend on how much free time I have to work on `warpped_mono`, but it shouldn't be longer than 2-3 months.
