### ISSUE TITLE
Project Future

### ISSUE THREAD

**Issue by winterSteve25** [FractalFir/wrapped_mono#8]
Hi there!

I just found this project and it looks really cool! Thanks for all the great work. I am currently looking into potentially writing a game engine, and this seems like a great way to integrate c# scripting into it. I was wondering if some of the planned and WIP features (especially the profiler) are still planned to be completed or if is it considered abandoned.

Cheers!

**Comment by FractalFir** [comment]
The project development is sadly frozen for the time being. I will fix bugs and accept pull requests, but I won't be actively developing it. So, it is unlikely those features will be coming any time soon.

Additionally, it is likely I will be working on a replacement for this project in the near (this year) future. 
`wrapped_mono` has some technical limitations - it uses mono, so only old C#(6) is supported. Supporting newer C# would require moving to CoreCLR, which would entail a total rewrite. This rewrite is not a priority for me - but I will need it at some point.

So, the project is not abandoned - it is in maintenance mode till I replace it.

If you need to use the newest .NET version, you may consider using [netcorehost](https://crates.io/crates/netcorehost/0.17.0). It is harder to use, since its APIs are very bare-bones.

**Comment by winterSteve25** [comment]
Understood, thanks for the info!
